// functions\src\services\types\service-errors.ts

export enum ServiceErrorCode {
  // Generic errors (1000-1999)
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  BAD_REQUEST = "BAD_REQUEST",

  // User specific errors (2000-2999)
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_SUBMISSION_LIMIT_EXCEEDED = "USER_SUBMISSION_LIMIT_EXCEEDED",
  USER_INVALID_TIER = "USER_INVALID_TIER",

  // Message specific errors (3000-3999)
  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  MESSAGE_ALREADY_PROCESSED = "MESSAGE_ALREADY_PROCESSED",
  MESSAGE_INVALID_STATUS = "MESSAGE_INVALID_STATUS",

  // Submission specific errors (4000-4999)
  SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND",
  SUBMISSION_ALREADY_PROCESSED = "SUBMISSION_ALREADY_PROCESSED",
  SUBMISSION_INVALID_TYPE = "SUBMISSION_INVALID_TYPE",
  SUBMISSION_PROCESSING_FAILED = "SUBMISSION_PROCESSING_FAILED",

  // External service errors (5000-5999)
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT",
  EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE",
}
